#!/usr/bin/env bash
#bash that copy to a remote server

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
file_path=$1
ip=$2
username=$3
identify_as_p=$4

scp -i "$identify_as_p" "$file_path" "$username@$ip:~/"
