#!/usr/bin/env bash
#bash to manage installment of nginx

sudo apt-get -y update
sudo apt-get install -y nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo sh -c 'echo "server {
	listen 80;
	server_name localhost;


	location / {
		root /var/www/html;
		index index.html;
	}
} " /etc/nginx/sites-available/default'

sudo service nginx restart

