#!/usr/bin/env bash
#bash to redirect the another page

sudo apt-get -y update
sudo apt-get -y install nginx

write_to_red=/etc/nginx/sites-available/default
sudo service nginx start
redi="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "40i $redi" $write_to_red
sudo service nginx restart
