#!/usr/bin/env bash
#Script that does create a file and store in its PID...

delete_at_2(){
	echo 'Y U no love me?!'
	rm -rf /var/run/myscript.pid
	exit
}

delete_at_15(){
	echo 'I hate the kill command'
	rm -rf /var/run/myscript.pid
	exit
}

trap "delete_at_2" 2
trap "delete_at_15" 15

echo "$$" > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
done
