#!/usr/bin/env bash
#Script to tell stroy of /etc/passwd
tell_s_file='/etc/passwd'

if [ -r "$tell_s_file" ]; then
	while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; do
		echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
	done < "$tell_s_file"
else
	echo "file does not exist"
fi
