#!/usr/bin/env bash
#write out the string Best School 10 time at 9th print hi
var='Best School'
counter=1

while [ $counter -ne 11 ];
do
	if [ $counter -eq 10 ]; then
		echo "Hi"
	fi
	echo "$var"
	((counter++))
done
