#!/usr/bin/env bash
#prints out Best School, 4 line prints bad luck and 8 line prints good luck
var='Best School'
counter=1

while [ $counter -ne 11 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "$var"
	fi
	((counter++))
done
