#!/usr/bin/env bash
#display the clock of 12 hours
h_count=0

while [ $h_count -ne 13 ]; do
	echo "Hour: $h_count"
	counter=1
	while [ $counter -ne 60 ]; do
		echo "$counter"
		((counter++))
	done
	((h_count++))
done
