#!/usr/bin/env bash
#script to check if a file exist or not
file_check='school'

if [ -e "$file_check" ]; then
	echo "school file exists"
	if [ -s "$file_check" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file_check" ];then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
