#!/usr/bin/env bash
#write over the hosts file

cp /etc/hosts ~/hosts.new
sed -i -e '/^$/,$!b' -e '$a\8.8.8.8\tfacebook.com' ~/hosts.new
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
