#!/usr/bin/env bash
#configure docker to run with user nginx
sudo kill -9 apache2
chomd 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
